### ISSUE TITLE
Setup fails because "service did not take the steps required by its unit configuration."

### ISSUE THREAD

**Issue by scttdavs** [ankane/setup-postgres#10]
Hi! My GH action kicked off today (haven't used it in a while, so not sure when this started) and it fails when setting up PG. It passed the last time I did this, some weeks back, so nothing's changed on my end. Seems there's an extra step that is required now? Here's the logs, where it's trying to run [this command](https://github.com/ankane/setup-postgres/blob/5cee36a4ea04be6f3c8ab818e500d585fa1d3dec/index.js#L150):

```
sudo systemctl start postgresql@16-main
Job for postgresql@16-main.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status postgresql@16-main.service" and "journalctl -xeu postgresql@16-main.service" for details.
node:child_process:966
    throw err;
    ^
Error: Command failed: sudo systemctl start postgresql@16-main
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at run (/home/runner/work/_actions/ankane/setup-postgres/v1/index.js:10:3)
    at Object.<anonymous> (/home/runner/work/_actions/ankane/setup-postgres/v1/index.js:150:3)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1[28](https://github.com/scttdavs/ep-server/actions/runs/12238483677/job/34137001517?pr=1343#step:6:29)8:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2189,
  stdout: null,
  stderr: null
}
Node.js v20.18.0
```

**Comment by ankane** [comment]
Hi @scttdavs, what OS version and Postgres version are you trying to run?

**Comment by ankane** [comment]
It looks like [CI is passing](https://github.com/ankane/setup-postgres/actions/runs/12280900558) for all supported versions of Ubuntu with Postgres 16.
